--A. BASIC QUERIES--
--1--
SELECT NAME, PROBLEM FROM CUSTOMERS;

--2--
SELECT PRODUCT_NAME, MRP, EXPIRY_DATE FROM MEDICINES;

--3--
SELECT NAME, USER_ID FROM USERS WHERE ROLE = 'MANAGER';

--4--
SELECT DISTINCT C.*
FROM CUSTOMERS C
JOIN SALES S ON C.CUSTOMER_ID = S.CUSTOMER_ID
JOIN MEDICINES M ON S.PRODUCT_CODE =
M.PRODUCT_CODE
WHERE M.PRODUCT_NAME = 'PARACETAMOL';

--5--
SELECT EMAIL FROM USERS WHERE ROLE <> 
'MANAGER';

--B. INTERMEDIATE QUERIES--
--6--
SELECT * FROM MEDICINES 
WHERE EXPIRY_DATE <= SYSDATE + 60;

--7--
SELECT * FROM MEDICINES
WHERE QUANTITY < 10;

--8--
SELECT DISTINCT C.NAME
FROM CUSTOMERS C
JOIN SALES S ON C.CUSTOMER_ID = S.CUSTOMER_ID
JOIN MEDICINES M ON S.PRODUCT_CODE =
M.PRODUCT_CODE
WHERE C.SEX = 'M' AND M.MRP > 50;

--9--
SELECT C.NAME, M.PRODUCT_NAME
FROM CUSTOMERS C
JOIN SALES S ON C.CUSTOMER_ID = S.CUSTOMER_ID
JOIN MEDICINES M ON S.PRODUCT_CODE =
M.PRODUCT_CODE;

--C. JOIN & AGGREGATION--
--11--
SELECT C.NAME, M.PRODUCT_NAME, S.QUANTITY_SOLD
FROM SALES S
JOIN CUSTOMERS C ON S.CUSTOMER_ID =
C.CUSTOMER_ID
JOIN MEDICINES M ON S.PRODUCT_CODE =
M.PRODUCT_CODE;

--12--
SELECT SUM (M.MRP * S.QUANTITY_SOLD) AS
TOTAL_SALES_AMOUNT
FROM SALES S
JOIN MEDICINES M ON S.PRODUCT_CODE =
M.PRODUCT_CODE;

--13--
SELECT PRODUCT_NAME
FROM MEDICINES
WHERE QUANTITY = (SELECT MAX(QUANTITY) FROM
MEDICINES);

--14--
SELECT COUNT(*) AS TOTAL_CUSTOMERS FROM 
CUSTOMERS;

--15--
SELECT M.PRODUCT_NAME, SUM(S.QUANTITY_SOLD)
AS TOTAL_SOLD
FROM SALES S
JOIN MEDICINES M ON S.PRODUCT_CODE =
M.PRODUCT_CODE
GROUP BY M.PRODUCT_NAME;

--D. COMPLEX QUERIES--
--16--
SELECT CUSTOMER_ID 
FROM SALES
GROUP BY CUSTOMER_ID
HAVING SUM(QUANTITY_SOLD)>5;

--17--
SELECT PRODUCT_NAME
FROM (
SELECT M.PRODUCT_NAME, SUM(M.MRP*S.QUANTITY_SOLD) AS
TOTAL_SALES
FROM SALES S
JOIN MEDICINES M ON S.PRODUCT_CODE =M.PRODUCT_CODE
GROUP BY M.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC)
WHERE ROWNUM <=3;

--18--
SELECT DISTINCT M.PRODUCT_NAME
FROM MEDICINES M 
JOIN SALES S ON M.PRODUCT_CODE = S.PRODUCT_CODE
WHERE M.QUANTITY =0;

--19--
SELECT DISTINCT C.NAME
FROM CUSTOMERS C
JOIN SALES S ON C.CUSTOMER_ID = S.CUSTOMER_ID
JOIN MEDICINES M ON S.PRODUCT_CODE = M.PRODUCT_CODE
WHERE M.EXPIRY_DATE < S.SALE_DATE;

--20--
SELECT U.NAME, COUNT(R.VIEWED_BY) AS REPORTS_VIEWED
FROM USERS U
LEFT JOIN REPORTS R ON U.USER_ID = R.VIEWED_BY
GROUP BY U.NAME;

--E.SUBQUERIES--
--21--
SELECT *FROM USERS WHERE USER_ID NOT IN (SELECT VIEWED_BY FROM REPORTS);

--22
SELECT C.*
FROM CUSTOMERS C
JOIN SALES S ON C.CUSTOMER_ID = S.CUSTOMER_ID
JOIN MEDICINES M ON S.PRODUCT_CODE =
M.PRODUCT_CODE
WHERE M.MRP = (SELECT MAX(MRP) FROM MEDICINES);

--23--
SELECT *FROM USERS
WHERE USER_ID NOT IN (SELECT VIEWED_BY 
FROM REPORTS);

--24--
SELECT * FROM CUSTOMERS 
WHERE AGE > (SELECT AVG(AGE)FROM CUSTOMERS);

--25--
SELECT DISTINCT M.PRODUCT_NAME
FROM MEDICINES M
JOIN SALES S ON M.PRODUCT_CODE =
S.PRODUCT_CODE
JOIN CUSTOMERS C ON S.CUSTOMER_ID =
C.CUSTOMER_ID
WHERE C.NAME LIKE 'A%';

--F.PRACTICAL SCENARIOS--
--26--
SELECT M.*
FROM MEDICINES M
JOIN SALES S ON M.PRODUCT_CODE =
S.PRODUCT_CODE
JOIN CUSTOMERS C ON S.CUSTOMER_ID =
C.CUSTOMER_ID
WHERE C.NAME = 'ALI'
AND M.EXPIRY_DATE < SYSDATE;

--27--
SELECT PRODUCT_NAME, QUANTITY
FROM MEDICINES
ORDER BY QUANTITY DESC;

--28--
SELECT CUSTOMER_ID
FROM SALES
GROUP BY CUSTOMER_ID
HAVING COUNT(DISTINCT PRODUCT_CODE) > 1;

--29--
UPDATE MEDICINES
SET QUANTITY = QUANTITY + 100
WHERE PRODUCT_NAME = 'PARACETAMOL';

--30--
SELECT M.PRODUCT_NAME,
SUM(M.MRP * S.QUANTITY_SOLD) AS
MONTHLY_SALES
FROM SALES S
JOIN MEDICINES M ON S.PRODUCT_CODE =
M.PRODUCT_CODE
WHERE S.SALE_DATE >=
ADD_MONTHS(TRUNC(SYSDATE), -1)
GROUP BY M.PRODUCT_NAME;

--G. ADVANCED--
--31--
SELECT PRODUCT_CODE, PRODUCT_NAME, COUNT(*)
FROM MEDICINES
GROUP BY PRODUCT_CODE, PRODUCT_NAME
HAVING COUNT(*)> 1;

--32--
ALTER TABLE MEDICINES ADD COST_PRICE NUMBER(8,2);


SELECT PRODUCT_NAME,
MRP,
COST_PRICE,
(MRP - COST_PRICE) AS PROFIT
FROM MEDICINES;

--33--
DELETE FROM MEDICINES WHERE EXPIRY_DATE < ADD_MONTHS(SYSDATE, -12);

--34--
SELECT TO_CHAR(S.SALE_DATE, 'YYYY-MM') AS MONTH,
SUM (S.QUANTITY_SOLD) AS TOTAL_SOLD
FROM SALES S
JOIN MEDICINES M ON S.PRODUCT_CODE =
M.PRODUCT_CODE
WHERE M.PRODUCT_NAME = 'PARACETAMOL'
AND S.SALE_DATE >= ADD_MONTHS(SYSDATE, -6)
GROUP BY TO_CHAR(S.SALE_DATE,'YYYY-MM')
ORDER BY MONTH;

--35--
SELECT C.NAME, SUM(S.QUANTITY_SOLD) AS
TOTAL_PURCHASED
FROM CUSTOMERS C
JOIN SALES S ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY C.NAME
ORDER BY TOTAL_PURCHASED DESC
FETCH FIRST 5 ROWS ONLY;
